### ISSUE TITLE
+

### ISSUE THREAD

**Issue by ravi-pandit14** [amandeepmittal/rnFirestoreUploadExample#1]

**Comment by amandeepmittal** [comment]
I don't get what's this issue is @ravi-pandit14?

**Comment by ravi-pandit14** [comment]
@amandeepmittal sorry for inconvenience. I have updated my issue. Please help!!!

**Comment by amandeepmittal** [comment]
@ravi-pandit14 I cannot to speak about the performance time you want to achieve but the you can fetch data from different docs using an uid in one round trip. For your reference, here are some likes that you can take a look at:

- https://stackoverflow.com/questions/46721517/google-firestore-how-to-get-document-by-multiple-ids-in-one-round-trip

- https://config9.com/apps/firebase/google-firestore-how-to-get-document-by-multiple-ids-in-one-round-trip/

Let me know if this is what you are looking for or not?

**Comment by ravi-pandit14** [comment]
@amandeepmittal  Thank you for reply! 
This is help full me for another implementation.
But In this case i will not get onSnapshot data (Realtime updates).
Currently i am using `Promise.all` for getting all data on 'Home' Page but it's take 7-10 seconds for display the data.
